title: Ross B. Alexander
description: Graduate student studying Aeronautics & Astronautics at Stanford University
baseurl: ''
url: https://rbalexander.me
permalink: slug
exclude:
  - Gemfile
  - Gemfile.lock
  - license
  - CNAME
plugins:
  - jekyll-sitemap
strict_front_matter: true
